-- MySQL Script generated by MySQL Workbench
-- Fri Jan  8 10:57:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quizmaster` ;

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quizmaster` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------
USE `quizmaster` ;

-- -----------------------------------------------------
-- Table `quizmaster`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `isCorrect` TINYINT NULL,
  `answer` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `quizmaster`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_answer_question1_idx` ON `quizmaster`.`answer` (`question_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coordinator_user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `lastChanged` DATE NULL,
  `coursecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_course_user1`
    FOREIGN KEY (`coordinator_user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_course_user1_idx` ON `quizmaster`.`course` (`coordinator_user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`credentials` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_credentials_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_credentials_user_idx` ON `quizmaster`.`credentials` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `groupName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_group_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `quizmaster`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_group_course1_idx` ON `quizmaster`.`group` (`course_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `question` VARCHAR(500) NULL,
  `attachedFile` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `quizmaster`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_question_quiz1_idx` ON `quizmaster`.`question` (`quiz_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `successDefinition` DOUBLE NULL,
  `timelimit` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_quiz_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `quizmaster`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_quiz_course1_idx` ON `quizmaster`.`quiz` (`course_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `studierichting` VARCHAR(45) NULL,
  `creationDate` DATE NULL,
  `deletionDate` DATE NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `quizmaster`.`user_answer_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`user_answer_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_answer_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_answer_log_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `quizmaster`.`answer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_user_answer_log_user1_idx` ON `quizmaster`.`user_answer_log` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_user_answer_log_answer1_idx` ON `quizmaster`.`user_answer_log` (`answer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`user_has_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `teacher_user_id` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `quizmaster`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_group_user2`
    FOREIGN KEY (`teacher_user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_user_has_group_group1_idx` ON `quizmaster`.`user_has_group` (`group_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_group_user1_idx` ON `quizmaster`.`user_has_group` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_group_user2_idx` ON `quizmaster`.`user_has_group` (`teacher_user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `quizmaster`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quizmaster`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `quizmaster`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_user_role_user1_idx` ON `quizmaster`.`user_role` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_user_role_role1_idx` ON `quizmaster`.`user_role` (`role_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


CREATE USER 'quizmasteruser'@'%' IDENTIFIED BY 'pwQuizMaster';
GRANT ALL PRIVILEGES ON quizmaster.* TO 'quizmasteruser'@'%';
